---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-crossplane-provider-ibm-cloud
  labels:
    app.kubernetes.io/instance: ibm-crossplane-provider-ibm-cloud
    app.kubernetes.io/managed-by: ibm-crossplane-provider-ibm-cloud
    app.kubernetes.io/name: ibm-crossplane-provider-ibm-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-crossplane-provider-ibm-cloud
subjects:
  - kind: ServiceAccount
    name: ibm-crossplane-provider-ibm-cloud
    namespace: ibm-common-services