apiVersion: iampolicymanagementv1.ibmcloud.crossplane.io/v1alpha1
kind: Policy
metadata:
  name: policy-access-postgres
spec:
  forProvider:
    type: access
    subjects:
    - attributes:
      - name: iam_id
        value: IBMid-100000KRAY
    roles:
    - roleId: crn:v1:bluemix:public:iam::::role:Administrator
    resources:
    - attributes:
      - name: accountId
        value: 0b5a00334eaf9eb9339d2ab48f20d7f5
        operator: stringEquals
      - name: serviceName
        value: postgres
  providerConfigRef:
    name: ibm-cloud