apiVersion: ibmcloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ibm-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: ibm-common-services
      name: provider-ibm-cloud-secret
      key: credentials
  region: us-south    
   