# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: crossplane-system
#   name: provider-ibm-cloud-secret
# type: Opaque
# data:
#    credentials: xxx
---
apiVersion: ibm-cloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ibm-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-ibm-cloud-secret
      key: credentials
  region: us-south    
   