apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: cos
spec:
  forProvider:
    name: mycos
    target: global
    serviceName: cloud-object-storage
    resourcePlanName: standard
    tags:
      - dev
  providerConfigRef:
    name: ibm-cloud