apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: mycloudant
spec:
  forProvider:
    name: mycloudant
    target: us-south
    resourceGroupName: default
    serviceName: cloudantnosqldb
    resourcePlanName: standard
    tags:
      - dev
  providerConfigRef:
    name: ibm-cloud