apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: mypostgres
spec:
  forProvider:
    name: mypostgres
    target: us-south
    resourceGroupName: default
    serviceName: databases-for-postgresql
    resourcePlanName: standard
    tags:
      - dev
    parameters:
      members_disk_allocation_mb: 32768
  providerConfigRef:
    name: ibm-cloud