apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: ibm-crossplane-provider-ibm-cloud
spec:
  controller:
    image: DOCKER_REGISTRY/ibm-crossplane-provider-ibm-cloud-controller:VERSION
